# Generated by Django 4.2.2 on 2024-04-04 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='date_borrowing',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
